---
# Group vars

etc_host_lines:
  - "{{ internal_ip.bastion }} bastion.bitsalt.com"
  - "{{ internal_ip.mysql01 }} mysql01.bitsalt.com"

server_dependencies:
  - fail2ban
  - certbot
  - python3-certbot-nginx
  - mariadb-client
  - python3-pymysql

nginx_dependencies:
  - nginx
  - mysql-client
  - python3-mysql
  - php-fpm
  - php-mysql

php_modules:
  - php-curl
  - php-cli
  - php-fpm
  - php-json
  - php-pdo
  - php-mysql
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-pear
  - php-bcmath
  - php-intl
  - php-zip

ssl:
  acme_challenge_type: http-01
  acme_directory: https://acme-v02.api.letsencrypt.org/directory
  acme_version: 2
  acme_email: jeff@bitsalt.com
  letsencrypt_live_dir: /etc/letsencrypt/live
  letsencrypt_dir: /etc/letsencrypt
  letsencrypt_keys_dir: /etc/letsencrypt/keys
  letsencrypt_csrs_dir: /etc/letsencrypt/csr
  letsencrypt_certs_dir: /etc/letsencrypt/certs
  letsencrypt_account_key: /etc/letsencrypt/account/account.key
  #letsencrypt_account_uri: https://acme-v02.api.letsencrypt.org/acme/acct/118997876

#   138.197.59.39 bitsalt.app01
# 45.55.122.176 bitsalt.app02
# 167.172.20.70 bitsalt.mysql01
# 157.245.14.169 bitsalt.bastion
# 142.93.64.130 bitsalt.xfiles
# 174.138.38.61 lessonbank