---
# Group vars

server_dependencies:
  - fail2ban
  - certbot
  - python3-certbot-nginx
  - mariadb-server
  - python3-pymysql
  - software-properties-common
  - awscli

# Existing databases
databases:
  - acct_bitsalt
  - bitsalt
  - jeffmoser
  - jumpstc8_main
  - kyaepl_prod
  - kyskillsupl
  - lessonbank
  - saltfin
  - seaisland
  - studbook_nas
  - taotedev
  - yourls
