---
# Group vars

server_dependencies:
  - fail2ban
  - certbot
  - python3-certbot-nginx
  - mariadb-server
  - python3-pymysql
  - software-properties-common
  - awscli

python_dependencies:
  - boto3
  - PyMySQL

# Existing databases
databases:
  - acctbitsalt
  - bitsalt
  - jeffmoser
  - jumpstartfarm
  - kyaeplprod
  - lessonbank
  - saltfin
  - seaisland
  - studbook
  - taotedev
  - yourls

# Databases no longer used
deleted_databases:
  - kyskillsupl
  - acctbitsalt
