---
# Group vars - many for testing purposes, but
# some are related to local dev environment setup.

php_version: "7.4-fpm"

test_group_ips:
  - 127.0.0.1
  - 192.168.0.1
  - 10.10.0.1

etc_host_lines:
  - "{{ internal_ip.app01 }} app01.bitsalt.com"
  - "{{ internal_ip.app02 }} app02.bitsalt.com"
  - "{{ internal_ip.mysql01 }} mysql01.bitsalt.com"
  - "{{ internal_ip.bastion }} bastion.bitsalt.com"

nginx_dependencies:
  - nginx
  - mysql-client
  - python3-mysql
  - php-fpm
  - php-mysql

# This needs to be reviewed
php_modules:
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
