# Configuration tasks file for nginx

- name: Write temporary site conf file prior to having SSL certs
  template:
    dest: "/etc/nginx/sites-available/{{ host.name }}.conf"
    src: nginx80.conf.j2
  tags:
    - install

- name: Make symlink to site conf file
  file:
    src: "/etc/nginx/sites-available/{{ host.name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ host.name }}.conf"
    state: link
  tags:
    - install
    - update
  notify: restart nginx

