# Install tasks for nginx

- name: Install Nginx
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
      "{{ nginx_dependencies }}"
  tags: install

- name: Nginx custom configuration
  file: 
    src: files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  tags: install
    
- name: Test nginx launch site
  debug:
    var: host
  tags:
    - test