---
# Install Nginx

- hosts: "{ hostname }"
  include_vars:
  sudo: yes
  tasks:
  - name: Update the apt cache
    apt:
      update_cache: yes
      cache_valid_time: 7200
  - name: Install Nginx
    apt:
      name: Nginx
      state: latest
