---
# tasks file for nginx

- name: Write new site conf file
  template:
    dest: "/etc/nginx/sites-available/{{ host.url }}.conf"
    src: nginx.conf.j2
  tags:
    - deploy

- name: Make symlink to site conf file
  file:
    src: "/etc/nginx/sites-available/{{ host.url }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ host.url }}.conf"
    state: link
  tags:
    - deploy
  notify: restart nginx

- name: Install Nginx
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
      "{{ nginx_dependencies }}"
  tags:
    - install

- name: Nginx custom configuration
  file: 
    src: files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags:
    - install
  notify: restart nginx
    
- name: Test nginx launch site
  debug:
    var: host
  tags:
    - test