---
- name: Backup databases to S3
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - ./secrets.yml

  tasks:
    # - name: Loop through databases
    #   ansible.builtin.debug:
    #     msg: "Databases: {{ databases }}"

    - name: List S3 buckets
      amazon.aws.s3_bucket:
        name: "{{ item }}"
        state: present
      loop: "{{ databases }}"
