---
- name: Backup databases to S3
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - ./secrets.yml
    - ./group_vars/local.yml

  tasks:
    - name: List S3 buckets
      amazon.aws.s3_bucket:
        name: "bitsalt-{{ item }}"
        state: present
        public_access: 
          block_public_policy: yes
      loop: "{{ databases }}"
