---
# Install new wordpress site

- hosts: "{{ host_name }}"
  vars_files:
    - ./secrets.yml
    - "./sites/{{ site_file }}.yml"
  
  roles:
    - role: mysqlDB
    - role: laravel
    - role: nginx
    
