---
# Install files to support Acme/Letsencrypt
- hosts: "{{ host_name }}"
  vars_files:
    - ./secrets.yml
    - "./sites/{{ site_file }}.yml"
  become: yes
  tasks:
  - name: Create required directories
    file:
      path: "/etc/letsencrypt/{{ item }}"
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=x,o=x
    with_items:
    - account
    - certs
    - csrs
    - keys
  
  - name: Generate an account key
    shell: "if [ ! -f {{ letsencrypt_account_key }} ]; then openssl genrsa 4096 | sudo tee {{ letsencrypt_account_key }}; fi"

  - name: Generate a private key
    shell: "openssl genrsa 4096 | sudo tee /etc/letsencrypt/keys/{{ host.name }}.key"

  - name: Generate Let's Encrypt CSR
    shell: "openssl req -new -sha256 -key /etc/letsencrypt/keys/{{ host.name }}.key -subj \"/CN={{ domain_name }}\" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf \"\n[SAN]\nsubjectAltName=DNS:{{ domain_name }},DNS:www.{{ domain_name }}\")) | sudo tee /etc/letsencrypt/csrs/{{ domain_name }}.csr"
    args:
      executable: /bin/bash

  - name: Set var name for challenge
    set_fact:
      reg_name: acme_challenge_{{ host.reg_name }}

  - name: Begin Let's Encrypt challenges
    community.crypto.acme_certificate:
      acme_directory: "{{ ssl.acme_directory }}"
      acme_version: "{{ ssl.acme_version }}"
      account_key_src: "{{ ssl.letsencrypt_account_key }}"
      account_email: "{{ ssl.acme_email }}"
      terms_agreed: 1
      challenge: "{{ ssl.acme_challenge_type }}"
      csr: "{{ ssl.letsencrypt_csrs_dir }}/{{ host.name }}.csr"
      dest: "{{ ssl.letsencrypt_certs_dir }}/{{ host.name }}.crt"
      fullchain_dest: "{{ ssl.letsencrypt_certs_dir }}/fullchain_{{ host.name }}.crt"
      remaining_days: 91
    register: "{{ reg_name }}"

  - name: Create .well-known/acme-challenge directory
    file:
      path: "{{ host.webroot }}/.well-known/acme-challenge"
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx

  - name: Implement http-01 challenge files
    copy:
      content: "{{ reg_name['challenge_data'][item]['http-01']['resource_value'] }}"
      dest: "{{ host.webroot }}/{{ reg_name['challenge_data'][item]['http-01']['resource'] }}"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    with_items:
    - "{{ host.name }}"
    - "www.{{ host.name }}"

  - name: Complete Let's Encrypt challenges
    community.crypto.acme_certificate:
      acme_directory: "{{ ssl.acme_directory }}"
      acme_version: "{{ ssl.acme_version }}"
      account_key_src: "{{ ssl.letsencrypt_account_key }}"
      account_email: "{{ ssl.acme_email }}"
      challenge: "{{ ssl.acme_challenge_type }}"
      csr: "{{ ssl.letsencrypt_csrs_dir }}/{{ host.name }}.csr"
      dest: "{{ ssl.letsencrypt_certs_dir }}/{{ host.name }}.crt"
      chain_dest: "{{ ssl.letsencrypt_certs_dir }}/chain_{{ host.name }}.crt"
      fullchain_dest: "{{ ssl.letsencrypt_certs_dir }}/fullchain_{{ host.name }}.crt"
      data: "{{ reg_name }}"
