---
# handlers file for nginx

- name: Test nginx configuration 
  ansible.builtin.shell:
    cmd: nginx -t 
  register: nginx_test_config
  listen: "restart nginx"

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: nginx_test_config.rc == 0
  listen: "restart nginx"
