---
# Install Nginx and related software
  - name: Install Nginx
    apt:
      name: "{ item }"
      update_cache: yes
      state: latest
      loop:
        - nginx
        - mysql-client
        - python3-mysql
        - php-fpm
        - php-mysql
  