---
# tasks file for webservers
- hosts: appservers
  become: yes
  vars_files:
    /home/jeff/ansible/bitsalt_ansible/secrets.yml
  tasks:
  # - name: debug
    # debug:
    #   msg: "become pass: {{ become_passwd }}"
  - name: Enable firewall
    include_tasks: app-firewall.yml
  - name: Add bastion keys 
    include_tasks: keys.yml
  # - name: Install software
  #   include_tasks: install.yml