---
# tasks file for nginx
- hosts: bastion
  strategy: debug
  become: no
  vars_files:
    - /home/jeff/ansible/bitsalt_ansible/secrets.yml
    - /home/jeff/ansible/bitsalt_ansible/playbooks/webserver/vars/main.yml
  tasks:
  - name: debug some stuff
    debug:
      msg: "hosts: {{ item[1] }}"
      #".key }} - {{ item.value }}"
    with_indexed_items: "{{ appserver_hosts }}"
    # with_dict: "{{ appserver_hosts }}"
